PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE "ac_assignments" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "parent_id" integer(8), "role_id" integer NOT NULL, "principal_id" integer NOT NULL, "node_id" integer(8) NOT NULL);
CREATE TABLE "ac_nodes" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "securable_type" varchar(40) NOT NULL, "securable_id" integer(8) NOT NULL, "block" boolean DEFAULT 'f' NOT NULL);
CREATE TABLE "ac_parents" ("parent_id" integer(8) NOT NULL, "child_id" integer(8) NOT NULL);
CREATE TABLE "ac_principals" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "subject_type" varchar(40) NOT NULL, "subject_id" integer NOT NULL);
CREATE TABLE "ac_roles" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(40) NOT NULL);
CREATE TABLE "ac_security_policy_items" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "permission" varchar(60) NOT NULL, "role_id" integer NOT NULL);
CREATE TABLE "records" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "field" integer, "name" varchar(255), "record_id" integer);
CREATE TABLE "records_records" ("from_id" integer, "to_id" integer);
CREATE TABLE "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(255));
CREATE TABLE "schema_migrations" ("version" varchar(255) NOT NULL);
INSERT INTO "schema_migrations" VALUES('20120525232117');
CREATE INDEX "index_ac_assignments_on_node_id" ON "ac_assignments" ("node_id");
CREATE INDEX "index_ac_assignments_on_parent_id" ON "ac_assignments" ("parent_id");
CREATE INDEX "index_ac_assignments_on_principal_id" ON "ac_assignments" ("principal_id");
CREATE INDEX "index_ac_assignments_on_role_id" ON "ac_assignments" ("role_id");
CREATE UNIQUE INDEX "index_ac_nodes_on_securable_type_and_securable_id" ON "ac_nodes" ("securable_type", "securable_id");
CREATE INDEX "index_ac_parents_on_child_id" ON "ac_parents" ("child_id");
CREATE UNIQUE INDEX "index_ac_parents_on_parent_id_and_child_id" ON "ac_parents" ("parent_id", "child_id");
CREATE UNIQUE INDEX "index_ac_principals_on_subject_type_and_subject_id" ON "ac_principals" ("subject_type", "subject_id");
CREATE UNIQUE INDEX "index_ac_roles_on_name" ON "ac_roles" ("name");
CREATE UNIQUE INDEX "index_ac_security_policy_items_on_role_id_and_permission" ON "ac_security_policy_items" ("role_id", "permission");
CREATE UNIQUE INDEX "unique_schema_migrations" ON "schema_migrations" ("version");
COMMIT;
