volumes:
  bundle:
  history:

services:
  lib:
    build: .
    entrypoint: ./.docker-config/entrypoint.sh
    environment:
      HISTFILE: /usr/local/hist/.bash_history
    depends_on:
      - db
    tmpfs:
      - /app/spec/app/log
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - history:/usr/local/hist

  db:
    image: mariadb:latest
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    tmpfs:
      - /var/lib/mysql
