services:
  lib:
    build: .
    volumes:
      - .:/app:cached
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    volumes:
      - /tmp/access-control-test:/var/lib/mysql
