FROM mariadb:10.6-focal

RUN echo "[mysqld]" >> /etc/mysql/conf.d/sql_mode.cnf
RUN echo "sql_mode = NO_ENGINE_SUBSTITUTION,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER" >> /etc/mysql/conf.d/sql_mode.cnf
