source 'https://rubygems.org'

gem 'rails', '~> 2.3.5'
gem 'access_control', :path => '../../'

platform :mri do
  gem 'mysql2', "< 0.3.0"
  gem 'sqlite3'
end

platform :jruby do
  gem 'activerecord-jdbcmysql-adapter'
  gem 'jdbc-mysql'
end

group :development do
  gem 'pry'
  gem 'pry-doc'
end
