development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: access_control_rcabralc_development
  pool: 5
  username: ed
  password: @mp1u$
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: access_control_rcabralc_test
  pool: 5
  username: ed
  password: @mp1u$
  socket: /var/run/mysqld/mysqld.sock
